# Generated by Django 6.0 on 2026-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEAM_PMO', 'Team PMO'), ('SENIOR_PMO', 'Senior PMO'), ('ADMIN', 'Admin'), ('FINANCE', 'Finance')], default='EMPLOYEE', max_length=20),
        ),
    ]
