# Generated by Django 6.0 on 2025-12-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('PMO', 'PMO'), ('ADMIN', 'Admin'), ('FINANCE', 'Finance')], default='EMPLOYEE', max_length=20),
        ),
    ]
