# Generated by Django 6.0 on 2026-01-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_designation_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEAM_PMO', 'Team PMO'), ('SENIOR_PMO', 'Senior PMO'), ('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('HR', 'HR')], default='EMPLOYEE', max_length=20),
        ),
    ]
