# Generated by Django 6.0 on 2026-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('OFFBOARDING', 'Offboarding'), ('EXITED', 'Exited')], default='ONBOARDING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
