# Generated by Django 6.0 on 2026-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_attachments/'),
        ),
    ]
