# Generated by Django 6.0 on 2026-02-05 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('AUTO', 'Auto Generated'), ('MANUAL', 'Manual')], max_length=10)),
                ('triggered_by', models.CharField(max_length=20)),
                ('quantity_needed', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING_FINANCE', 'Pending Finance Approval'), ('APPROVED_FINANCE', 'Finance Approved'), ('APPROVED_HR', 'HR Approved'), ('ORDER_PLACED', 'Order Placed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING_FINANCE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice_attachment', models.FileField(blank=True, null=True, upload_to='purchase_invoices/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
