# Generated by Django 6.0 on 2025-12-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_assetdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdetails',
            old_name='employee',
            new_name='user',
        ),
    ]
