# Generated by Django 6.0 on 2026-02-19 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchaserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdetails',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='assetdetails',
            name='quantity_issued_date',
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='quantity_issued',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='triggered_by',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MOUSE', 'Mouse'), ('KEYBOARD', 'Keyboard'), ('MONITOR', 'Monitor'), ('PRINTER', 'Printer'), ('OTHER', 'Other')], max_length=50)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_qr_code', models.CharField(blank=True, max_length=150, null=True)),
                ('total_quantity', models.IntegerField(default=1)),
                ('available_quantity', models.IntegerField(default=1)),
                ('issued_quantity', models.IntegerField(default=0)),
                ('minimum_stock_level', models.IntegerField(default=0)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('processor_generation', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_size', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_type', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics_card', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_health', models.IntegerField(blank=True, null=True)),
                ('os_installed', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size_inch', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('panel_type', models.CharField(blank=True, choices=[('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA'), ('OLED', 'OLED')], max_length=20, null=True)),
                ('touchscreen', models.BooleanField(blank=True, null=True)),
                ('curved_screen', models.BooleanField(blank=True, null=True)),
                ('input_ports', models.JSONField(blank=True, null=True)),
                ('usb_hub_available', models.BooleanField(blank=True, null=True)),
                ('speakers_available', models.BooleanField(blank=True, null=True)),
                ('connectivity_type', models.CharField(blank=True, choices=[('USB', 'USB Wired'), ('BLUETOOTH', 'Bluetooth'), ('WIRELESS', 'Wireless')], max_length=50, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('warranty_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('SCRAPPED', 'Scrapped'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='NEW', max_length=20)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=150, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='asset_attachments/')),
                ('warranty_documents', models.FileField(blank=True, null=True, upload_to='asset_warranty_docs/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_records', to='inventory.asset'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='inventory.asset'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
