# Generated by Django 6.0 on 2026-02-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('REPAIRED', 'Repaired'), ('SCRAPPED', 'Scrapped'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', max_length=20),
        ),
    ]
