# Generated by Django 6.0 on 2026-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='barcode_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('SCRAPPED', 'Scrapped'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', max_length=20),
        ),
    ]
