# Generated by Django 6.0.2 on 2026-03-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_asset_barcode_qr_code_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='barcode_qr_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
