# Generated by Django 6.0.2 on 2026-03-06 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_asset_asset_tag_alter_asset_barcode_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
