# Generated by Django 6.0.2 on 2026-03-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_asset_vendor_name_asset_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='issue_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
