# Generated by Django 6.0.2 on 2026-03-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_assetdetails_issue_date_assetdetails_issue_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='issued_quantity',
            new_name='quantity_issued',
        ),
    ]
