# Generated by Django 6.0.2 on 2026-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_issued_quantity_asset_quantity_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('PARTIAL_RETURN', 'Partial Return')], default='ISSUED', max_length=20),
        ),
    ]
