# Generated by Django 6.0.2 on 2026-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_assetdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT & Technology'), ('FURNITURE', 'Furniture'), ('ELECTRONICS', 'Electronics'), ('STATIONERY', 'Stationery'), ('OTHER', 'Other')], default='OTHER', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
