# Generated by Django 6.0 on 2026-01-02 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='team_pmo_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING_TEAM_PMO', 'Pending Team PMO'), ('PENDING_SENIOR_PMO', 'Pending Senior PMO'), ('PENDING_ADMIN', 'Pending Admin'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], default='PENDING_TEAM_PMO', max_length=30),
        ),
        migrations.CreateModel(
            name='AssignedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ticket_rows', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Tickets.ticket')),
            ],
            options={
                'db_table': 'assigned_tickets',
            },
        ),
    ]
