# Generated by Django 6.0 on 2026-01-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_ticket_created_by_role_ticket_team_pmo_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
