# Generated by Django 6.0 on 2026-01-05 11:01

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_ticket_escalation_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedticket',
            name='action_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignedticket',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('COMPLETED', 'Completed'), ('STATUS_UPDATED', 'Status Updated'), ('AUTO_ESCALATED', 'Auto Escalated')], db_index=True, default='ASSIGNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING_TEAM_PMO', 'Pending Team PMO'), ('PENDING_SENIOR_PMO', 'Pending Senior PMO'), ('PENDING_ADMIN', 'Pending Admin'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING_TEAM_PMO', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='team_pmo_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='assignedticket',
            index=models.Index(fields=['ticket', 'action_date'], name='assigned_ti_ticket__5708dd_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedticket',
            index=models.Index(fields=['assigned_to', 'action_date'], name='assigned_ti_assigne_a0382f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'team_pmo_deadline'], name='tickets_tic_status_250ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['employee'], name='tickets_tic_employe_10b558_idx'),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets_ticket',
        ),
    ]
