# Generated by Django 6.0 on 2026-01-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_alter_assignedticket_action_date_and_more'),
        ('users', '0003_role_user_role_obj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('sla_hours', models.PositiveIntegerField(default=4)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='step_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(default='DEFAULT', max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ticket_type', 'version')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tickets.workflow'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['step_deadline'], name='tickets_tic_step_de_52b017_idx'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Tickets.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_order')},
        ),
    ]
