# Generated by Django 6.0 on 2026-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0006_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
