# Generated by Django 6.0 on 2026-02-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0007_workflow_description_workflow_workflow_name'),
        ('users', '0007_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_steps', to='users.role'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_steps', to='users.role'),
        ),
    ]
