# Generated by Django 6.0 on 2026-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_workflowstep_target_role_alter_workflowstep_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='role_step_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
