# Generated by Django 6.0 on 2026-02-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0009_workflowstep_role_step_order'),
        ('users', '0007_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['role', 'step_order']},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'role', 'step_order')},
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='role_step_order',
        ),
    ]
